"""add year to uploads

Revision ID: 2cecc58c9d20
Revises: a04322bc9dba
Create Date: 2026-08-14 16:07:45.957971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cecc58c9d20'
down_revision: Union[str, Sequence[str], None] = 'a04322bc9dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exam_study_materials', 'uploads', ['document_id'], ['id'])
    op.create_foreign_key(None, 'exam_study_materials', 'exams', ['exam_id'], ['id'])
    op.add_column('uploads', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_uploads_year'), 'uploads', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_year'), table_name='uploads')
    op.drop_column('uploads', 'year')
    op.drop_constraint(None, 'exam_study_materials', type_='foreignkey')
    op.drop_constraint(None, 'exam_study_materials', type_='foreignkey')
    # ### end Alembic commands ###
