"""add chat sessions

Revision ID: 38c3754d74b6
Revises: c120f4cf91ac
Create Date: 2026-08-06 00:10:55.393877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c3754d74b6'
down_revision: Union[str, Sequence[str], None] = 'c120f4cf91ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_chat_messages_document_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_column('chat_messages', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_document_id'), 'chat_messages', ['document_id'], unique=False)
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###
