"""add exam fields to uploads

Revision ID: 4ad4dff8c5e7
Revises: 38c3754d74b6
Create Date: 2026-08-08 20:10:05.377739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad4dff8c5e7'
down_revision: Union[str, Sequence[str], None] = '38c3754d74b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.add_column(
    'uploads',
    sa.Column(
        'document_type',
        sa.String(),
        nullable=False,
        server_default='study_material',
    )
)
    op.alter_column('uploads', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_uploads_exam_id'), 'uploads', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_exam_id'), table_name='uploads')
    op.alter_column('uploads', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('uploads', 'document_type')
    op.drop_column('uploads', 'exam_id')
    # ### end Alembic commands ###
