"""add pattern analysis

Revision ID: 54c6422cdf51
Revises: 2cecc58c9d20
Create Date: 2026-08-20 11:27:11.825556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c6422cdf51'
down_revision: Union[str, Sequence[str], None] = '2cecc58c9d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('pattern_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'pattern_analysis')
    # ### end Alembic commands ###
