"""restore exam association

Revision ID: a77bbe7e9cf3
Revises: 32079d26c5c5
Create Date: 2026-08-09 12:02:49.730331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77bbe7e9cf3'
down_revision: Union[str, Sequence[str], None] = '32079d26c5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_uploads_exam_id'), 'uploads', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_exam_id'), table_name='uploads')
    op.drop_column('uploads', 'exam_id')
    # ### end Alembic commands ###
